### ISSUE TITLE
List of KB sources?

### ISSUE THREAD

**Issue by myedibleenso** [clulab/bioresources#15]
It sure would be nice to have a document that gives the KB(s) serving as the source for each resource.  Perhaps this could just be included in the README?  

For example, I was trying to figure out the source KB for a tissue type context mention produced by REACH.  The mention was assigned the grounding id `tissuelist:TS-0591`.  Am I right in thinking that http://www.uniprot.org/docs/tisslist.txt is the source associated with the `tissuelist` namespace?

**Comment by hickst** [comment]
These have been documented several times in the past in our publications but I'm sure those lists are probably out-of-date. Would a wiki page here answer the issue?

**Comment by hickst** [comment]
I forgot to answer the question: yes, our tissue KB is derived from the Uniprot Tissue list.

**Comment by MihaiSurdeanu** [comment]
Yes, a Wiki page would be nice.
Mihai

**Comment by hickst** [comment]
Added Wiki page documenting KBs used: [https://github.com/clulab/bioresources/wiki/KBs](https://github.com/clulab/bioresources/wiki/KBs)

**Comment by myedibleenso** [comment]
This is very useful, thanks.

Perhaps it should be linked from the README as well?
