### ISSUE TITLE
Extend Gene_or_gene_product groundings with HGNC

### ISSUE THREAD

**Issue by bgyori** [clulab/bioresources#25]
Currently, bioresources only draws on UniProt to gather names and synonyms of `Gene_or_gene_product` entities. However, at least for human genes/proteins, many essential synonyms are available in HGNC that UniProt does not contain. One class of proteins for which this is a critical gap is ion channels such as `SCN10A`, which is most commonly referred to as `Nav1.8` in the literature (other examples include Nav1.5, Nav1.7, etc., all of which NER and grounding fail on due to missing synonyms). These synonyms are available in HGNC, and therefore it would make sense to add that as a source as well. I could implement it in a way that redundancies with synonyms from UniProt are resolved.

**Comment by MihaiSurdeanu** [comment]
This would be great. Thanks @bgyori !
