### ISSUE TITLE
Rename "pfam" to "family"

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/bioresources#28]
Hi Ben,
It looks like you used the label "family" in your recent changes, but NER-Grounding-Override.tsv.gz uses "pfam" for the same thing, which confuses Reach. Should we rename pfam to family? Can you please implement whatever you think makes sense and let me know?
Thanks!

**Comment by hickst** [comment]
Just a note that PFAM is a specific protein family database, which we used previously, which is why that entry might still be pointing to PFAM. Ben may have obviated the need to continue to use PFAM.
PFAM: https://pfam.xfam.org/

**Comment by MihaiSurdeanu** [comment]
@bgyori: please ignore this PR, for now. 
I misread the output. The issue is something else.

**Comment by MihaiSurdeanu** [comment]
False alarm. Closing.
