### ISSUE TITLE
Correct labeling of amino acids has been lost

### ISSUE THREAD

**Issue by hickst** [clulab/bioresources#3]
Amino acids are being labeled as Sites instead of simple chemicals. This causes Reach grounding to fail to identify them. All amino acids are being correctly generated into the NER Simple_chemical.tsv.gz file.

**Comment by hickst** [comment]
Dummy comment on real issue to test recent integration with Slack.

**Comment by MihaiSurdeanu** [comment]
This must come from the Reach Site rules. @myedibleenso?
The CRF does not recognize sites.

**Comment by myedibleenso** [comment]
I'll need a more information.  We'll need tests, so the more examples you can give the better.  These can be hard to tell apart, I think. 

Also, can you tell me which rules are to blame, @hickst?

**Comment by hickst** [comment]
mention text: tyrosine
List(Site)
    ------------------------------
    Rule => site_long
    Type => CorefTextBoundMention
    ------------------------------
    Site|List(Site) => tyrosine
    grounding: KBResolution(tyrosine, uaz, UAZ00001, )
    ------------------------------

**Comment by myedibleenso** [comment]
Often when an amino acid is mentioned, it is used to reference an underspecified site (ex. "tyrosine phosphorylation").  Even though this isn't an exact location, it is providing us with some information about where a reaction is taking place.

**Comment by MihaiSurdeanu** [comment]
Let's discuss tomorrow. I think the only place where we use amino acids is
to recognize sites. So we might do the right thing.

**Comment by hickst** [comment]
For our purposes, we are interested only in amino acids as sites so this is not a problem.
