### ISSUE TITLE
KB Cleanups

### ISSUE THREAD

**Issue by hickst** [clulab/bioresources#9]
[ ] Remove unused manual KBs.
[ ] Add custom KB from MITRE model.

**Comment by hickst** [comment]
Repurposed manual KBs to have 2nd highest priority and filled them with MITRE model data as initial content.

**Comment by MihaiSurdeanu** [comment]
Why _2nd highest priority_ and not 1st priority? This KB should override
everything.

**Comment by hickst** [comment]
Perhaps I should have said "highest" non-auxiliary priority.
- We need these manual files to participate in NER generation which auxiliaries don't.
- I have checked these entries against NMZ's auxiliary file and they do not conflict.
- I have included a new test suite for these which passes.
